global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "demo-app"
    static_configs:
      - targets: ["demo-app:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
